layout_spectrum: 0.40968583184294405
typography_spectrum: 0.1319022049336224
color:
  brandStrength: 0.713667476918954
  lightness: 0.29721092711175134
  saturation: 0.9100850587350197
  rhythmicContrast: 0.17701743142338158
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6fc16e82-ab39-493f-9369-4eec50b25452.png
name: HexaCubist
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/599f199e-7118-4066-8db2-5cd199fa87bf.png
title: HexaCubist
content: []
description: My personal portfolio of projects I've worked on
purpose:
  - type: contact
    url: 'mailto:me@hexacubist.com'
    label: Contact me
  - type: external
    url: 'http://github.com/HexaCubist'
    label: Github
