layout_spectrum: 0.32806222991824224
typography_spectrum: 0.13233711153361025
color:
  brandStrength: 0.8839445095036252
  lightness: 0.21903499165854168
  saturation: 0.7811183380236905
  rhythmicContrast: 0.6258362099392764
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6fc16e82-ab39-493f-9369-4eec50b25452.png
name: HexaCubist
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/599f199e-7118-4066-8db2-5cd199fa87bf.png
title: HexaCubist
content: []
description: My personal portfolio of projects I've worked on
purpose:
  - type: contact
    url: 'mailto:me@hexacubist.com'
    label: Contact me
  - type: external
    url: 'http://github.com/HexaCubist'
    label: Github
