layout_spectrum: 0.3338907269158834
typography_spectrum: 0.14659964437882353
color:
  brandStrength: 0.59152274463003
  lightness: 0.8480444242408739
  saturation: 0.8334417490691574
  rhythmicContrast: 0.45702072486355166
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6fc16e82-ab39-493f-9369-4eec50b25452.png
name: HexaCubist
navigation:
  - name: Argolia Events
    url: 'http://event.argolia.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/599f199e-7118-4066-8db2-5cd199fa87bf.png
title: HexaCubist
content: []
description: My personal portfolio and portal
purpose:
  - type: contact
    url: 'mailto:me@hexacubist.com'
    label: Contact me
  - type: external
    url: 'http://github.com/HexaCubist'
    label: Github
