typography_spectrum: 0.49962823325768113
color:
  brandStrength: 0.13950469135306776
  lightness: 0.24762174556963146
  saturation: 0.6202938801143318
  rhythmicContrast: 0.8072816787753254
  brandColors:
    - '#703030'
    - '#2F343B'
    - '#7E827A'
    - '#E3CDA4'
    - '#C77966'
github: true
layout_spectrum: 0.06325269863009453
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6fc16e82-ab39-493f-9369-4eec50b25452.png
name: HexaCubist
navigation:
  - name: Argolia Events
    url: 'http://event.argolia.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/599f199e-7118-4066-8db2-5cd199fa87bf.png
title: HexaCubist
content: []
description: My personal portfolio and portal
purpose:
  - type: contact
    url: 'mailto:touch@hexacubist.com'
    label: Contact me
